### ISSUE TITLE
any dataset download link or data examples?

### ISSUE THREAD

**Issue by anxu829** [CharlesWu123/SPLERGE#1]

**Comment by CharlesWu123** [comment]
I am using the ICDAR2013 table dataset. There are also other tabular datasets that can be used, and you need to deal with the data format yourself。
ICDAR2013 : https://roundtrippdf.com/en/
PubTabNet : https://github.com/ibm-aur-nlp/PubTabNet
ICDAR2019_cTDaR : http://sac.founderit.com/index.html

**Comment by anxu829** [comment]
thank you for your reply !

**Comment by anxu829** [comment]
> I am using the ICDAR2013 table dataset. There are also other tabular datasets that can be used, and you need to deal with the data format yourself。
> ICDAR2013 : https://roundtrippdf.com/en/
> PubTabNet : https://github.com/ibm-aur-nlp/PubTabNet
> ICDAR2019_cTDaR : http://sac.founderit.com/index.html

thank you for your reply

**Comment by daaituzi** [comment]
> I am using the ICDAR2013 table dataset. There are also other tabular datasets that can be used, and you need to deal with the data format yourself。
> ICDAR2013 : https://roundtrippdf.com/en/
> PubTabNet : https://github.com/ibm-aur-nlp/PubTabNet
> ICDAR2019_cTDaR : http://sac.founderit.com/index.html

请问你只使用了 ICDAR2013作为训练集就跑出来样例中的效果了吗？谢谢

**Comment by CharlesWu123** [comment]
对，就用了 ICDAR2013 作为训练集。由于工作原因，在这方面就没有再做深入研究了。
